#!/bin/bash
# This file is generated by hh, see https://github.com/moold/hh for details.
#> hujiang
../target/release/fastmd5 data.bin > checksums.md5  # 2025-08-26 11:40:35
../target/release/fastmd5 -c checksums.md5  # 2025-08-26 11:40:42
